import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { StatsGrid } from '../components/xyz'
import { HeaderMiddle } from '../components/header2'
import { TableReviews } from '../components/table'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Graphlane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMiddle links={[
        {
          "link": "/about",
          "label": "Home"
        },
        {
          "link": "/learn",
          "label": "Features"
        },
        {
          "link": "/pricing",
          "label": "Pricing"
        }

      ]}></HeaderMiddle>
      <h3 style={{
        
    paddingLeft: '20px',
    paddingTop: '20px',
    boxSizing: 'content-box',
  }} >Track your impermanant losses</h3>
      <StatsGrid data={[
    {
      "title": "Revenue",
      "icon": "receipt",
      "value": "13,456",
      "diff": 34
    },
    {
      "title": "Profit",
      "icon": "coin",
      "value": "4,145",
      "diff": -13
    },
    {
      "title": "Coupons usage",
      "icon": "discount",
      "value": "745",
      "diff": 18
    },
    {
      "title": "New customers",
      "icon": "user",
      "value": "188",
      "diff": -30
    }
  ]} ></StatsGrid>
  <br></br>
  <br></br>

  <TableReviews data={[
     {
      "title": "Foundation",
      "author": "Isaac Asimov",
      "year": 1951,
      "reviews": {
        "positive": 2223,
        "negative": 259
      }
    },
    {
      "title": "Frankenstein",
      "author": "Mary Shelley",
      "year": 1818,
      "reviews": {
        "positive": 5677,
        "negative": 1265
      }
    },
    {
      "title": "Solaris",
      "author": "Stanislaw Lem",
      "year": 1961,
      "reviews": {
        "positive": 3487,
        "negative": 1845
      }
    },
    {
      "title": "Dune",
      "author": "Frank Herbert",
      "year": 1965,
      "reviews": {
        "positive": 8576,
        "negative": 663
      }
    },
    
  ]}></TableReviews>
      
           
    </>
  )
}
